### ISSUE TITLE
Option to ignore errors for decoding

### ISSUE THREAD

**Issue by KorbinianBarthuber** [infsec-consult/emotet-url-extractor#1]
I suggest to add the option to ignore errors for the decode part:

> script = script_bytes.decode('UTF-16LE',errors="ignore")

This way the script also works for samples with a bad encoded script (eg https://www.malware-traffic-analysis.net/2020/09/02/index.html ).

**Comment by infsec-consult** [comment]
Thanks, added in the new version.
